### ISSUE TITLE
Allow notifications in group chats

### ISSUE THREAD

**Issue by alex-denisov** [mhkafadar/notifine#17] opened 2023-03-14 21:43 UTC
Hi @mhkafadar !
Your bot looks promising and is a great replacement for integram gitlab_bot.
I've noticed that Gitlab notifications to group chats failing with the following error: 
`Hook executed successfully but returned HTTP 502 <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> </body> </html>`

It would be great to have the same notification list (ex: push, pipelines) in group chats.
I guess you have disabled the Groups function in Telegram bot settings.

**Comment by mhkafadar** [comment] 2023-03-15 17:44
Hello @alex-denisov ,

Thanks for bringing this issue to my attention! You're right, the group feature is available, but there's a bug affecting group IDs with more than 10 characters. I'll be working on a fix for this issue and will push an update soon to address it.

I appreciate your help in identifying this problem and for reaching out to me on Telegram. Your assistance has been invaluable in debugging and pinpointing the root cause of the issue. Your feedback and support are crucial for the continuous improvement of the project. Please feel free to report any other issues you may encounter or suggest any enhancements you'd like to see in the future.

**Comment by hatamiarash7** [comment] 2023-07-03 14:36
I have this issue too

**Comment by mhkafadar** [comment] 2023-07-03 21:56
Interesting,
@hatamiarash7 I will check the issue soon.

**Comment by diazzaid** [comment] 2023-08-22 03:24
> Hi @mhkafadar ! Your bot looks promising and is a great replacement for integram gitlab_bot. I've noticed that Gitlab notifications to group chats failing with the following error: `Hook executed successfully but returned HTTP 502 <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> </body> </html>`
> 
> It would be great to have the same notification list (ex: push, pipelines) in group chats. I guess you have disabled the Groups function in Telegram bot settings.



> 

has the webhook_url in .env been filled using the domain?
before i got the same error.
so make sure the webhook url in .env is the same as that filled in the gitlab webhook

**Closed** 2023-09-02 16:08 UTC
Labels: bug
